services:
  db:
    image: postgres:16
    container_name: cwt-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./causalehr_backup:/causalehr_backup:ro
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cwt-app:
    image: causalknowledgetrace:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cwt-app
    ports:
      - "3838:3838"
    env_file:
      - .env
    environment:
      - DB_HOST=db  # This overrides the DB_HOST from .env file
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/causalknowledgetrace

volumes:
  pgdata: